OPENAI_API_KEY = "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"
PASSWORD = "Priyav@1983!"
